version: '3.7'
services:
  dart:
    build: .
    container_name: dartRealTimeApi
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - peer
    networks:
      chatNetwork:
        ipv4_address: 172.18.0.2
  peer:
    image: peerjs/peerjs-server
    container_name: peerjs
    command: bash -c "peerjs --port 9000 --key peerjs --path /call"
    ports:
      - 9000:9000
    networks:
      chatNetwork:
        ipv4_address: 172.18.0.4
  postgres:
    image: postgres:14.1
    container_name: postgresFlutter
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      POSTGRES_PASSWORD: "CaZ1DiWXdh4PWJuuwdk6YjREXdcpjcgt"
    volumes:
      - test_data:/var/lib/postgresql/data
    networks:
      chatNetwork:
        ipv4_address: 172.18.0.3
volumes:
  test_data:
networks:
  chatNetwork:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/16
         gateway: 172.18.0.1