version: '3.7'
services:
  dart:
    build: .
    container_name: dartRealTimeApi
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1
    container_name: postgresFlutter
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      POSTGRES_PASSWORD: "CaZ1DiWXdh4PWJuuwdk6YjREXdcpjcgt"
    volumes:
      - test_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    container_name: redisFlutter
    ports:
      - '8091:6379'
    command: redis-server --requirepass "ihgnjIN_-kUIQSu32NpZkotYneteq0NH"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  test_data:
