#!/bin/sh

# Start docker
echo "Starting docker"
docker-compose up --build --detach

if command -v netstat &> /dev/null
then
  while ! netstat -tna | grep 'LISTEN' | grep -q '.8090'; do
    echo "Waiting for Postgres..."
    sleep 2 # time in seconds, tune it as needed
  done
else
  while ! ss -tulpn | grep LISTEN | grep :8090; do
    echo "Waiting for Postgres..."
    sleep 2
  done
fi

sleep 2

echo "Postgres is ready"

docker cp ./generated/tables-serverpod.pgsql postgresFlutter:/docker-entrypoint-initdb.d/tables-serverpod.pgsql && docker cp ./generated/tables.pgsql postgresFlutter:/docker-entrypoint-initdb.d/tables.pgsql 

sleep 5

docker exec -u postgres postgresFlutter  psql test postgres -f docker-entrypoint-initdb.d/tables-serverpod.pgsql && docker exec -u postgres postgresFlutter  psql test postgres -f docker-entrypoint-initdb.d/tables.pgsql


echo "Stopping docker"
docker compose stop
